#!/bin/bash
#CIT470 Project 2 LDAP Installation/Configuration Script
#Team 1: Austin Kelly, Zoey Koza, Randy Clark, Kasey Cottier and Chris Pischl
#March 17th, 2019        * Lines of Code, excluding comments*
#If a user requests -h or --help at command line, start small script while logging all output.
if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  echo "Usage: `basename $0` [Start the NFS Server script by using this command: ./install-nfs-server]" | tee -a nfs-install.log
else
#Add users and passwords
echo "Adding users: ..." | tee -a nfs-install.log
add_users () {
useradd -c "Austin Kelly" -s /bin/bash -d /home/kellya -m kellya | tee -a ldap-install.log
echo "CIT470" | passwd kellya --stdin | tee -a ldap-install.log
useradd -c "Zoey Koza" -s /bin/bash -d /home/kozaz -m  kozaz | tee -a ldap-install.log
echo "CIT470" | passwd kozaz --stdin | tee -a ldap-install.log
useradd -c "Randy Clark" -s /bin/bash -d /home/clarkr -m clarkr | tee -a ldap-install.log
echo "CIT470" | passwd clarkr --stdin | tee -a ldap-install.log
useradd -c "Kasey Cottier" -s /bin/bash -d /home/cottierk -m  cottierk | tee -a ldap-install.log
echo "CIT470" | passwd cottierk --stdin | tee -a ldap-install.log
useradd -c "Chris Pischl" -s /bin/bash -d /home/pischlc -m  pischlc | tee -a ldap-install.log
echo "CIT470" | passwd pischlc --stdin | tee -a ldap-install.log
}

#Download, install, and configure LDAP
echo "Configuring LDAP: ..." | tee -a nfs-install.log
config_ldap () {
yum -y install openldap-servers openldap-clients | tee -a ldap-install.log
systemctl start slapd
systemctl enable slapd
ldapmodify -Y EXTERNAL  -H ldapi:/// -f update1.ldif | tee -a ldap-install.log
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
chown ldap:ldap /var/lib/ldap/*
ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/core.ldif | tee -a ldap-install.log
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif | tee -a ldap-install.log
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif | tee -a ldap-install.log
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif | tee -a ldap-install.log
ldapadd -x -w CIT470 -D "cn=Manager,dc=team1,dc=nku,dc=edu" -f /base.ldif | tee -a ldap-install.log
firewall-cmd --permanent --add-service=ldap | tee -a ldap-install.log
firewall-cmd --reload | tee -a ldap-install.log
}

#Migrate users into LDAP
echo "Migrating user account info into LDAP: ..." | tee -a nfs-install.log
migrate_users () {
yum -y install migrationtools | tee -a ldap-install.log
grep "test" /etc/passwd >> /users
grep "test" /etc/group >> /groups
grep "kellya" /etc/passwd >> /users
grep "kellya" /etc/group >> /groups
grep "kozaz" /etc/passwd >> /users
grep "kozaz" /etc/group >> /groups
grep "clarkr" /etc/passwd >> /users
grep "clarkr" /etc/group >> /groups
grep "cottierk" /etc/passwd >> /users
grep "cottierk" /etc/group >> /groups
grep "pischlc" /etc/passwd >> /users
grep "pischlc" /etc/group >> /groups
cp -f /migrate_common.ph /usr/share/migrationtools/migrate_common.ph 
/usr/share/migrationtools/migrate_passwd.pl /users /users.ldif | tee -a ldap-install.log
/usr/share/migrationtools/migrate_group.pl /groups /groups.ldif | tee -a ldap-install.log
ldapadd -x -w CIT470 -D "cn=Manager,dc=team1,dc=nku,dc=edu" -f /users.ldif | tee -a ldap-install.log
ldapadd -x -w CIT470 -D "cn=Manager,dc=team1,dc=nku,dc=edu" -f /groups.ldif | tee -a ldap-install.log
}

#Download and install diradm
echo "Configuring diradm utility: ..." | tee -a nfs-install.log
config_diradm () {
cd /usr/local
wget http://www.hits.at/diradm/diradm-1.3.tar.gz | tee -a ldap-install.log
tar zxvf diradm-1.3.tar.gz | tee -a ldap-install.log
cd /
mv /diradm.conf /etc/diradm.conf
}

add_users
config_ldap
migrate_users
config_diradm
fi
