#!/bin/bash
#CIT470 Project 2 NFS Installation Script
#Team 1: Austin Kelly, Zoey Koza, Randy Clark, and Kasey Cottier
#March 9th, 2019        *24 Lines of Code, excluding comments*
#If a user requests -h or --help at command line, start small script while logging all output.
if [ "$1" == "-h" ] || [ "$1" == "--help" ];
then echo "Usage: `basename $0` [Start the NFS Server script by using this command: ./install-nfs-server]" ; exit 0 ; fi | tee -a nfs-install.log

#Install NFS package(s), start the required services and enable them at startup while logging all output.
echo "Installing NFS and enabling the required services: ..." | tee -a nfs-install.log ;
yum -y install nfs-utils >& 1 >> nfs-install.log && systemctl enable rpcbind nfs-server >& 1 >> nfs-install.log ;
systemctl start rpcbind nfs-server >& 1 >> nfs-install.log && echo "NFS Installed and Services Enabled." | tee -a nfs-install.log ;
#Create a new primary partition logging all output. Spacing on lines 16-20 is crucial for the partition to succeed.
echo "Creating a New Partition: ..." | tee -a nfs-install.log	
fdisk /dev/sda <<EOF
n
p


w
EOF
partprobe /dev/sda >& 1 >> nfs-install.log && echo "New Partition has been Succesfully Created." | tee -a nfs-install.log

#Formating partition to XFS, Mounting the new partition, and Editing the fstab/export file. See detailed echo statements below.
echo "Formatting disk to XFS: ..." | tee -a nfs-install.log ; mkfs.xfs /dev/sda4 -f >& 1 >> nfs-install.log && xfs_repair /dev/sda4 >& 1 >> nfs-install.log && echo "Format has been changed to XFS." | tee -a nfs-install.log ;
echo "Mounting the newly created partition: ..." | tee -a nfs-install.log && mount /dev/sda4 /home >& 1 >> nfs-install.log && echo "The new partition has been mounted!" | tee -a nfs-install.log ;
echo "Editing the fstab file: ..." | tee -a nfs-install.log && echo "/dev/sda4        /home    xfs    defaults    0 0" >> /etc/fstab >& 1 >> nfs-install.log && echo "fstab file updated!." | tee -a nfs-install.log ;
echo "Editing the home export file: ..." | tee -a nfs-install.log ; echo "/home 10.2.6.0/23(rw,sync,no_root_squash,no_all_squash)" >> /etc/exports | tee -a nfs-install.log ;
echo "Exporting home directory: ..." >& 1 >> nfs-install.log ; exportfs -a  >& 1 >> nfs-install.log && echo "Home directory exported!" | tee -a nfs-install.log ;
#Firewall Configuration: tcp and udp NFS ports allowed.
echo "Configuring firewall for NFS Ports: ..." | tee -a nfs-install.log ; firewall-cmd --zone=public --add-port=2049/tcp --permanent >& 1 >> nfs-install.log ;
firewall-cmd --zone=public --add-port=111/tcp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=20048/tcp --permanent >& 1 >> nfs-install.log ;
firewall-cmd --zone=public --add-port=2049/udp --permanent >& 1 >> nfs-install.log ; firewall-cmd --zone=public --add-port=111/udp --permanent >& 1 >> nfs-install.log ;
firewall-cmd --zone=public --add-port=20048/udp --permanent >& 1 >> nfs-install.log && firewall-cmd --reload >& 1 >> nfs-install.log && echo "Firewall configured for NFS!" | tee -a nfs-install.log
