#!/bin/bash
#CIT470 Project 2 LDAP Installation/Configuration Script
#Team 1: Austin Kelly, Zoey Koza, Randy Clark, Kasey Cottier and Chris Pischl
#March 17th, 2019        * Lines of Code, excluding comments*
#If a user requests -h or --help at command line, start small script while logging all output.
if [ "$1" == "-h" ] || [ "$1" == "--help" ];
then echo "Usage: `basename $0` [Start the LDAP Install Script by using this command: ./install-ldap-server]" ; exit 0 ; fi | tee -a ldap-install.log

yum install openldap-servers openldap-clients -y
cd /etc/openldap/slapd.d/cn=config
ldapmodify -Y EXTERNAL -H ldapi:/// -f /root/update1.ldif 
systemctl start slapd.service
systemctl enable slapd.service
ldapadd -x -D "cn=Manager,dc=team1,dc=nku,dc=edu" -W -f /etc/openldap/slapd.d/cn\=config/team1.ldif
firewall-cmd --zone=public --add-port=389/tcp --permanent
firewall-cmd --zone=public --add-port=636/tcp --permanent
systemctl stop slapd
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
chown -R ldap:ldap /var/lib/ldap
yum install nss_ldap -y
yum install migrationtools -y
mv /root/migrate_common.ph /usr/share/migrationtools
mv /root/base.ldif /usr/share/migrationtools
systemctl start slapd
ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/core.ldif
ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/nis.ldif
ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/inetorgperson.ldif
systemctl stop slapd
chown -R ldap:ldap /var/lib/ldap
slapadd -v -l base.ldif
cd /usr/share/migrationtools
./migrate_group.pl /etc/group > group.ldif
slapadd -v -l group.ldif
chown -R ldap.ldap /var/lib/ldap
systemctl start slapd

